# LAB 02.03 - Pandas

<a target="_blank" href="https://colab.research.google.com/github/rramosp/ai4eng.v1/blob/main/content/LAB%2002.03%20-%20PANDAS.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

replicating local resources

In [18]:
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L02.03", varname="student");

logging in as mariaf.atencia@udea.edu.co... please wait

-------------
using course session ai4eng.v1.udea.r4::2026.1
success!! you are logged in
-------------

In [8]:
import numpy as np
import pandas as pd

## Task 1: Extract data

we have a dataframe of items with a price and, **sometimes**, with an extra column (`margin`).

You will have to complete a function that will **filter** the dataframe selecting the rows:

- whose price is > 100
- **OR** whose margin is >10, if the column `margin` is present

your function must return **A LIST** with the item ids of the selected rows

For instance, with the following dataframe

             price  category
    itemid                  
    56556   108.15       2.0
    73065    83.54       2.0
    36619   114.42       0.0
    73414    82.94       0.0
    13410   115.13       2.0
    66153    91.50       1.0
    77380    85.82       0.0
    73249    95.95       0.0
    11654   100.22       2.0
    11972    77.16       1.0

your must return the following list:

     [56556, 36619, 13410, 11654]
     
But if you get the following dataframe

             price  category  margin
    itemid                          
    39059    98.11       0.0   11.04
    19526    98.11       1.0   11.25
    78176    94.34       1.0   10.51
    50948   102.37       1.0   10.77
    12111    98.07       1.0    8.50
    56191    98.53       1.0   11.65
    38887    91.49       2.0   11.24
    77915   117.30       0.0    8.64
    55010    96.13       0.0    8.95
    45925    98.59       1.0   10.45
    
you must return the following list

    [39059, 19526, 78176, 50948, 56191, 38887, 77915, 45925]

In [6]:
def create_df(missing=False, n=10):
    itemid   = np.random.randint(100000, size=n)+1000
    category = np.random.randint(3, size=n)
    price    = np.round(np.random.normal(loc=100, scale=10, size=n),2)
    margin   = np.round(np.random.normal(loc=10, scale=1, size=n),2)

    if missing:
        nmissing = np.random.randint(len(price)//2)+2
        price[np.random.permutation(len(price))[:nmissing]] = np.nan

    d = pd.DataFrame(np.r_[[price, category, margin]].T, index=itemid, columns=["price", "category", "margin"])
    d.index.name="itemid"
    if np.random.random()>.5:
        d = d[d.columns[:2]]

    return d

In [6]:
d = create_df()
d

         price  category
itemid
70977   114.37       2.0
27136    96.56       0.0
91122    97.15       0.0
46426    83.00       1.0
80831    98.59       1.0
71100   116.25       0.0
21352    85.04       2.0
68236   111.04       1.0
65933    97.81       1.0
40263   103.02       1.0

In [10]:
def select_items(df):
    # make sure to make a copy in case you modify the original df
    df = df.copy()

    condition = df["price"] > 100

    if "margin" in df.columns:
        condition = condition | (df["margin"] > 10)

    result = df[condition].index.tolist()

    return result

**manually check your answer**

In [11]:
d = create_df()
d

         price  category
itemid
1702     93.90       1.0
42066    95.63       2.0
76938   105.51       0.0
31598    95.74       0.0
79911   101.70       0.0
36801   102.49       1.0
85312    94.08       1.0
22877   103.59       1.0
19770    96.43       0.0
57080   113.03       0.0

In [12]:
select_items(d)

[76938, 79911, 36801, 22877, 57080]

**submit your code**

In [13]:
student.submit_task(globals(), task_id="task_01");

## Task 2: Group statistics

Complete the following function so that it returns a dataframe with the average, max and min **prices** per category.

For instance, for the following dataframe

             price  category  margin
    itemid                          
    17946    93.85       1.0   10.64
    61190    91.72       1.0    9.76
    39639   100.16       1.0   10.67
    17791   110.44       2.0    9.65
    7333    101.05       1.0    9.69
    77362   122.33       0.0   11.14
    92646   108.13       2.0   10.58
    27797    85.52       2.0   10.88
    31746    97.56       0.0    9.75
    12355   101.04       2.0    9.51
    
you should return the following dataframe

                 media  maximo  minimo
    categoria                         
    0         109.9450  122.33  97.56
    1          96.6950  101.05  91.72
    2         101.2825  110.44  85.52
    
observe that your result
- must not be a **multilevel** columnset.
- the column names and the index name must be **exactly** as in the example.
- the **index** must be of type **int**.

In [64]:
def get_stats(df):
    # make sure to make a copy in case you modify the original df
    df = df.copy()
    media = 0
    maximo = 0
    minimo = 0
    df ["categoria"] = df["category"].astype(int)
    result = df.groupby("categoria")["price"].agg(
    media = 'mean',
    maximo = 'max',
    minimo = 'min'
)
    return result

**manually check your answer**

In [45]:
d = create_df()
d

         price  category  margin
itemid
32778   104.42       1.0   10.21
21623    90.91       0.0   10.80
45644   104.45       0.0   10.21
14477    87.85       2.0    9.67
9999     98.13       0.0   10.52
21045    94.43       0.0   10.47
79959   108.86       0.0   10.46
91114   118.87       1.0   10.46
64016    94.60       2.0   10.58
37378    95.73       1.0    9.41

In [65]:
get_stats(d)

             media  maximo  minimo
categoria
0           99.356  108.86   90.91
1          106.340  118.87   95.73
2           91.225   94.60   87.85

**submit your code**

In [66]:
student.submit_task(globals(), task_id="task_02");

## Task 3: Fill in missing data

Fill in the missing data in the **price** column with the following procedure:

- compute the mean and std of the avaialable prices
- sample from a normal distribution with the computed mean and std (see [`np.random.normal`])(https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html), as many samples as missing data
- substitute the missing values with the samples

For instance, for this input dataframe:

             price  category  margin
    itemid                          
    18922      NaN       1.0   10.32
    69500   121.25       1.0   10.22
    76442    90.25       1.0   12.60
    33863   106.51       0.0   10.26
    15904    95.87       1.0   11.51
    41946   103.47       2.0    9.85
    85451    93.08       2.0    9.56
    70028   116.68       1.0    9.11
    26860      NaN       2.0    9.71
    12807    91.48       0.0    9.77
    
your solution might be similar to this (not exactly the same as you will be sampling data):


                 price  category  margin
    itemid                              
    18922    97.441188       1.0   10.32
    69500   121.250000       1.0   10.22
    76442    90.250000       1.0   12.60
    33863   106.510000       0.0   10.26
    15904    95.870000       1.0   11.51
    41946   103.470000       2.0    9.85
    85451    93.080000       2.0    9.56
    70028   116.680000       1.0    9.11
    26860   103.294843       2.0    9.71
    12807    91.480000       0.0    9.77
    
    
**WARN**: your function must not modify the original dataframe, make a copy of the input dataframe, fill the values in the copy and return it.

**HINT**: use the [`isna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isna.html) method of a dataframe or a series.

In [9]:
d = create_df(missing=True)
d

         price  category
itemid
71680    97.05       1.0
22512      NaN       2.0
77871   103.99       0.0
68264   118.53       0.0
30987   104.34       2.0
62394      NaN       1.0
22351   100.99       2.0
41103      NaN       0.0
37902   103.66       0.0
54010      NaN       0.0

In [13]:
def fillna(df):
    # make sure to make a copy in case you modify the original df
    df_copy = df.copy()

    # Calculate mean and std from non-missing prices
    promedio = df_copy["price"].mean()
    desviacion = df_copy["price"].std()

    # Identify missing values
    missing_mask = df_copy["price"].isna()
    num_missing = missing_mask.sum()

    # Sample from a normal distribution
    normal_samples = np.random.normal(promedio, desviacion, size=num_missing)

    # Fill missing values with the samples
    df_copy.loc[missing_mask, "price"] = normal_samples

    return df_copy

**check manually your code**

In [11]:
d = create_df(missing=True)
d

         price  category
itemid
46678    99.13       0.0
39390      NaN       2.0
86380   103.52       1.0
38529   101.26       1.0
55274      NaN       1.0
97249      NaN       2.0
15036   109.60       1.0
46789    93.75       0.0
30718    81.72       2.0
27850      NaN       0.0

In [14]:
fillna(d)

             price  category
itemid
46678    99.130000       0.0
39390   107.354508       2.0
86380   103.520000       1.0
38529   101.260000       1.0
55274   102.537789       1.0
97249   103.489785       2.0
15036   109.600000       1.0
46789    93.750000       0.0
30718    81.720000       2.0
27850    84.753761       0.0

**submit your code**

In [19]:
student.submit_task(globals(), task_id="task_03");